# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/faraday-net_http_persistent/all/faraday-net_http_persistent.rbi
#
# faraday-net_http_persistent-1.2.0

module Faraday
end
class Faraday::Adapter
end
class Faraday::Adapter::NetHttpPersistent < Faraday::Adapter::NetHttp
end
module Faraday::NetHttpPersistent
end
