# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/faraday-em_synchrony/all/faraday-em_synchrony.rbi
#
# faraday-em_synchrony-1.0.0

module Faraday
end
class Faraday::Adapter
end
class Faraday::Adapter::EMSynchrony < Faraday::Adapter
  include Faraday::Adapter::EMHttp::Options
end
module Faraday::EmSynchrony
end
