# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/faraday-em_http/all/faraday-em_http.rbi
#
# faraday-em_http-1.0.0

module Faraday
end
class Faraday::Adapter
end
class Faraday::Adapter::EMHttp < Faraday::Adapter
  include Faraday::Adapter::EMHttp::Options
end
module Faraday::Adapter::EMHttp::Options
end
class Faraday::Adapter::EMHttp::Manager
end
module Faraday::EmHttp
end
