# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/faraday-httpclient/all/faraday-httpclient.rbi
#
# faraday-httpclient-1.0.1

module Faraday
end
class Faraday::Adapter
end
class Faraday::Adapter::HTTPClient < Faraday::Adapter
end
module Faraday::HTTPClient
end
