# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/faraday-multipart/all/faraday-multipart.rbi
#
# faraday-multipart-1.0.3

module Faraday
end
module Faraday::Multipart
end
class Faraday::Multipart::CompositeReadIO
end
class Faraday::Multipart::ParamPart
end
class Faraday::Multipart::Middleware < Faraday::Request::UrlEncoded
end
