# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/faraday-retry/all/faraday-retry.rbi
#
# faraday-retry-1.0.3

module Faraday
end
class Faraday::RetriableResponse < Faraday::Error
end
module Faraday::Retry
end
class Faraday::Retry::Middleware < Faraday::Middleware
end
class Faraday::Retry::Middleware::Options < Anonymous_Faraday_Options_38
end
