# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/faraday_middleware/all/faraday_middleware.rbi
#
# faraday_middleware-1.2.0

module Faraday
end
class Faraday::Request < Anonymous_Struct_37
end
class Faraday::Response
end
module FaradayMiddleware
end
class FaradayMiddleware::ResponseMiddleware < Faraday::Middleware
end
module FaradayMiddleware::OptionsExtension
end
class Faraday::RequestOptions < Anonymous_Faraday_Options_32
  include FaradayMiddleware::OptionsExtension
end
class FaradayMiddleware::ParseJson < FaradayMiddleware::ResponseMiddleware
end
class FaradayMiddleware::ParseJson::MimeTypeFix < FaradayMiddleware::ResponseMiddleware
end
