# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/faraday-excon/all/faraday-excon.rbi
#
# faraday-excon-1.1.0

module Faraday
end
class Faraday::Adapter
end
class Faraday::Adapter::Excon < Faraday::Adapter
end
module Faraday::Excon
end
