# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/image_processing/all/image_processing.rbi
#
# image_processing-1.12.1

module ImageProcessing
end
module ImageProcessing::Chainable
end
class ImageProcessing::Builder
  include ImageProcessing::Chainable
end
class ImageProcessing::Pipeline
end
class ImageProcessing::Processor
end
class ImageProcessing::Error < StandardError
end
