# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/mrkt/all/mrkt.rbi
#
# mrkt-1.2.1

module Mrkt
end

class Mrkt::Errors
end

class Mrkt::Errors::Error < StandardError
end

class Mrkt::Errors::Unknown < Mrkt::Errors::Error
end

class Mrkt::Errors::EmptyResponse < Mrkt::Errors::Error
end

class Mrkt::Errors::AuthorizationError < Mrkt::Errors::Error
end

class Mrkt::Errors::RequestEntityTooLarge < Mrkt::Errors::Error
end

class Mrkt::Errors::EmptyAccessToken < Mrkt::Errors::Error
end

class Mrkt::Errors::AccessTokenInvalid < Mrkt::Errors::Error
end

class Mrkt::Errors::AccessTokenExpired < Mrkt::Errors::Error
end

class Mrkt::Errors::AccessDenied < Mrkt::Errors::Error
end

class Mrkt::Errors::RequestTimedOut < Mrkt::Errors::Error
end

class Mrkt::Errors::HTTPMethodNotSupported < Mrkt::Errors::Error
end

class Mrkt::Errors::MaxRateLimit < Mrkt::Errors::Error
end

class Mrkt::Errors::DailyQuotaReached < Mrkt::Errors::Error
end

class Mrkt::Errors::APITemporarilyUnavailable < Mrkt::Errors::Error
end

class Mrkt::Errors::InvalidJSON < Mrkt::Errors::Error
end

class Mrkt::Errors::RequestedResourceNotFound < Mrkt::Errors::Error
end

class Mrkt::Errors::System < Mrkt::Errors::Error
end

class Mrkt::Errors::InvalidContentType < Mrkt::Errors::Error
end

class Mrkt::Errors::RecordNotFound < Mrkt::Errors::Error
end

class Mrkt::Errors::DisabledFeature < Mrkt::Errors::Error
end

class Mrkt::Errors::TypeMismatch < Mrkt::Errors::Error
end

class Mrkt::Errors::MissingParamater < Mrkt::Errors::Error
end

class Mrkt::Errors::UnspecifiedAction < Mrkt::Errors::Error
end

class Mrkt::Errors::LeadNotFound < Mrkt::Errors::Error
end

class Mrkt::Errors::LeadAlreadyExists < Mrkt::Errors::Error
end

class Mrkt::Errors::FieldNotFound < Mrkt::Errors::Error
end

class Mrkt::Errors::MultipleLeadsMatching < Mrkt::Errors::Error
end

class Mrkt::Errors::PartitionAccessDenied < Mrkt::Errors::Error
end

class Mrkt::Errors::PartitionNameUnspecified < Mrkt::Errors::Error
end

class Mrkt::Errors::PartitionUpdateDenied < Mrkt::Errors::Error
end

class Mrkt::Errors::FieldNotSupported < Mrkt::Errors::Error
end

class Mrkt::Errors::InvalidCookieValue < Mrkt::Errors::Error
end

class Mrkt::Errors::ObjectNotFound < Mrkt::Errors::Error
end

class Mrkt::Errors::FailedToCreateObject < Mrkt::Errors::Error
end

class Mrkt::Errors::LeadNotInList < Mrkt::Errors::Error
end

class Mrkt::Errors::TooManyImports < Mrkt::Errors::Error
end

class Mrkt::Errors::ObjectAlreadyExists < Mrkt::Errors::Error
end

class Mrkt::Errors::CRMEnabled < Mrkt::Errors::Error
end

class Mrkt::Errors::ImportInProgress < Mrkt::Errors::Error
end

class Mrkt::Errors::TooManyCloneToProgram < Mrkt::Errors::Error
end

class Mrkt::Errors::CompanyUpdateNotAllowed < Mrkt::Errors::Error
end

class Mrkt::Errors::ObjectInUse < Mrkt::Errors::Error
end

class Mrkt::Errors::ProgramStatusNotFound < Mrkt::Errors::Error
end

class Mrkt::Errors::CustomObjectNotEnabled < Mrkt::Errors::Error
end

class Mrkt::Errors::MaxActivityTypeLimitReached < Mrkt::Errors::Error
end

class Mrkt::Errors::MaxFieldLimitReached < Mrkt::Errors::Error
end

class Mrkt::Errors::BulkExportQuotaExceeded < Mrkt::Errors::Error
end

class Mrkt::Errors::UnsupportedFilterType < Mrkt::Errors::Error
end

class Mrkt::Errors::DuplicateObjectFoundInInput < Mrkt::Errors::Error
end

class Mrkt::Errors::InvalidRunAtDate < Mrkt::Errors::Error
end

class Mrkt::Errors::CustomObjectDiscardDraftFailed < Mrkt::Errors::Error
end

class Mrkt::Errors::FailedToCreateActivity < Mrkt::Errors::Error
end

class Mrkt::Errors::MergeLeadsCallFailedDueToFieldLength < Mrkt::Errors::Error
end

module Mrkt::Faraday
end

class Mrkt::Faraday::ParamsEncoder
end

module Mrkt::FaradayMiddleware
end

module Mrkt::Connection
end

module Mrkt::Authentication
end

module Mrkt::CrudHelpers
end

module Mrkt::CrudActivities
end

module Mrkt::CrudCampaigns
end

module Mrkt::CrudLeads
end

module Mrkt::CrudLists
end

module Mrkt::ImportLeads
end

module Mrkt::ImportCustomObjects
end

module Mrkt::CrudCustomObjects
end

module Mrkt::CrudCustomActivities
end

module Mrkt::CrudPrograms
end

module Mrkt::CrudProgramMembers
end

module Mrkt::CrudAssetStaticLists
end

module Mrkt::CrudAssetFolders
end

class Mrkt::Client
  include Mrkt::Authentication
  include Mrkt::Connection
  include Mrkt::CrudActivities
  include Mrkt::CrudAssetFolders
  include Mrkt::CrudAssetStaticLists
  include Mrkt::CrudCampaigns
  include Mrkt::CrudCustomActivities
  include Mrkt::CrudCustomObjects
  include Mrkt::CrudHelpers
  include Mrkt::CrudLeads
  include Mrkt::CrudLists
  include Mrkt::CrudProgramMembers
  include Mrkt::CrudPrograms
  include Mrkt::ImportCustomObjects
  include Mrkt::ImportLeads
end
