# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/multipart-post/all/multipart-post.rbi
#
# multipart-post-2.1.1

class CompositeReadIO
end
class UploadIO
end
module Parts
end
module Parts::Part
end
class Parts::ParamPart
  include Parts::Part
end
class Parts::FilePart
  include Parts::Part
end
class Parts::EpiloguePart
  include Parts::Part
end
